name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #- name: Build the Docker image
        #run: docker build -t mohammedbilal98/webserver:latest .

      - name: Build and Push Docker image
        env:
          IMAGE_TAG: 3  # Define your image tag here
        run: |
          docker build -t mohammedbilal98/webserver:${IMAGE_TAG} .
          docker push mohammedbilal98/webserver:${IMAGE_TAG}
      
      #- name: Push Docker image to registry
        #run: docker push mohammedbilal98/webserver:latest
    
      - name: Update deployment.yaml
        run: |
          sed -i "s|image: mohammedbilal98/webserver:TAG_NAME|image: mohammedbilal98/webserver:${IMAGE_TAG}|g" deployment.yaml 

      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Wait for deployment to stabilize
        run: |
          kubectl rollout status deployment/wisecow --timeout=2m
          kubectl get all

      - name: Test service URLs
        run: |
          minikube service list
          minikube service wisecow --url
      
      - name: Test service URLs
        run: |
          kubectl get pod -o wide
          kubectl port-forward wisecow 80:4499

          curl  "http://192.168.49.2:4499"
