name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

     
      - name: Build and Push Docker image
        env:
          IMAGE_TAG: 3  
        run: |
          docker build -t mohammedbilal98/webserver:${IMAGE_TAG} .
          docker push mohammedbilal98/webserver:${IMAGE_TAG}
      
          
      - name: Update deployment.yaml
        run: |
          sed -i "s|image: mohammedbilal98/webserver:TAG_NAME|image: mohammedbilal98/webserver:${IMAGE_TAG}|g" deployment.yaml 

      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest

      - name: Setup TLS
        run : |
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj "/CN=wisecow.webserver.com"
          kubectl create secret tls tls-secret --key tls.key --cert tls.crt

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f ingress.yaml

      - name: Wait for deployment to stabilize
        run: |
          kubectl rollout status deployment/wisecow --timeout=2m
          kubectl get all

      - name: Test service URLs
        run: |
          minikube service list
          minikube service wisecow --url

